import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ReactNode } from 'react'
import Link from 'next/link'
import { AuthProvider } from '@/contexts/AuthContext'
import HeaderNav from '@/components/HeaderNav'
import DDWLogo from '@/components/DDWLogo'
import SplashScreen from '@/components/SplashScreen'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface LayoutProps {
  children: ReactNode
}

export default function Layout({ children }: LayoutProps) {
  return (
    <html lang="ko" className={`${inter.variable}`}>
      <body className="font-sans antialiased">
        <AuthProvider>
          <SplashScreen />
          <div className="min-h-screen bg-gradient-to-br from-purple-50/20 to-white">
            {/* Header */}
            <header className="fixed w-full top-0 z-50 backdrop-blur-md bg-white/80 border-b border-gray-200/80">
              <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                <div className="flex justify-between items-center h-16">
                  <Link
                    href="/"
                    className="flex items-center"
                    aria-label="DDW 홈으로"
                  >
                    <DDWLogo className="h-8 w-auto" />
                  </Link>
                  <HeaderNav />
                </div>
              </div>
            </header>

            {/* Main Content */}
            <main className="pt-16 flex-grow">{children}</main>

            {/* Footer */}
            <footer className="bg-white border-t border-gray-200">
              <div className="max-w-7xl mx-auto py-12 px-4 sm:px-6 lg:px-8">
                <p className="text-center text-sm text-gray-500">
                  &copy; 2025 DDW. All rights reserved.
                </p>
              </div>
            </footer>
          </div>
        </AuthProvider>
      </body>
    </html>
  )
}
